---
title: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(plotly)
library(leaflet)
library(p8105.datasets)
library(forcats)
library(dplyr)
library(stringr)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, echo = FALSE}
data(instacart)
set.seed(7)
instacart_df = 
  instacart %>% 
  select(-c("product_id","eval_set", "aisle_id","department_id")) %>%
  sample_n(5000)
```

```{r, echo = FALSE}
instacart_df_clean =
  instacart_df %>% 
  mutate(order_hour_of_day = factor(order_hour_of_day),
         order_id = as.character(order_id),
         order_dow = factor(order_dow),
         order_dow = recode(order_dow,
             "0" = "Sunday",
             "1" = "Monday",
             "2" = "Tuesday",
             "3" = "Wednesday",
             "4" = "Thursday",
             "5" = "Friday",
             "6" = "Saturday",)
         )

instacart_df_clean %>% 
  group_by(order_dow, order_hour_of_day) %>% 
  summarize(total = n()) %>% 
  ungroup() %>% 
  mutate(text_label = str_c("Hour of day: ", order_hour_of_day, "h", "\nTotal orders: ", total, " orders")) %>%
  plot_ly(x = ~order_hour_of_day, 
          y = ~total,
          type = "scatter", mode = "line",
          color = ~order_dow,
          text = ~text_label, 
          alpha = 0.7) %>%
  layout(title = "Total number of orders per day by hour (from random sample of 5000 obs)",
         xaxis = list(title = "Hour of the day", tickangle = 0),
         yaxis = list(title = "Order count")
         )
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r message = FALSE, warning = FALSE, echo = FALSE}
instacart_df_clean %>% 
filter(reordered == 1 & days_since_prior_order < 8) %>% 
  count(aisle) %>% 
  top_n(20) %>% 
  mutate(aisle = fct_reorder(aisle, desc(n)),
        text_label = str_c("Count: ", n, " products")) %>% 
  plot_ly(x = ~aisle, 
          y = ~ n,
          type = "scatter", mode = "markers",
          text = ~text_label, 
          alpha = 0.9) %>%
  layout(title = "Top 10 aisles reordered from within 7 days (random sample of 5000 obs)",
         yaxis = list(title = "Number of reorders"),
         xaxis = list(title = "Aisle name", tickangle = 45)
         )
```

### Chart C

```{r, warning = FALSE, message = FALSE, echo = FALSE}
instacart_df_clean %>% 
filter(aisle %in% c("fresh fruits", "fresh vegetables", "packaged vegetables fruits", "yogurt")) %>% 
  group_by(order_dow, aisle) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count)) %>% 
  slice(1:3) 
  
  
```

