---
title: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(plotly)
library(leaflet)
library(p8105.datasets)
library(forcats)
library(dplyr)
library(stringr)
```

Column {data-width=500}
-----------------------------------------------------------------------
### Top 3 products in top 3 aisles ordered each day
```{r, echo = FALSE}
data(instacart)
set.seed(7)
instacart_df = 
  instacart %>% 
  select(-c("product_id","eval_set", "aisle_id","department_id")) %>%                       #select variables of interest
  sample_n(5000)          #make a random sample of 5000 observations

#cleaning data
instacart_df_clean =
  instacart_df %>% 
  mutate(order_hour_of_day = factor(order_hour_of_day), #make factor some variables 
         order_id = as.character(order_id),
         order_dow = factor(order_dow),
         order_dow = recode(order_dow,   #recode order_dow from numerical digits into day of week 
             "0" = "Sun",
             "1" = "Mon",
             "2" = "Tue",
             "3" = "Wed",
             "4" = "Thu",
             "5" = "Fri",
             "6" = "Sat",)
         )

#plot to get top 3 products ordered each day of week among top 3 aisles
plot1 = instacart_df_clean %>% 
filter(aisle %in% c("fresh fruits", "fresh vegetables", "yogurt", "packaged vegetables fruits")) %>% 
  group_by(order_dow, 
           product_name) %>%    #group by day of order and product name
  summarize(total = n()) %>%    #count number of product name in group
  arrange(desc(total)) %>%      #arrange number of products in descending order
  slice(1:3) %>%                #get top 3 product counts for each day of week
  ungroup() %>%    
  mutate(product_name = 
          fct_reorder(
            product_name, desc(total))) %>% 
  ggplot(aes(x = order_dow,     #graphing bar plot using ggplot 
             y = total,
             fill = product_name)) + 
  geom_bar(stat = "identity",
           position = position_dodge()) +
  viridis::scale_color_viridis(
    discrete = TRUE) + 
  labs(x = "Day of week",
       y = "Order count") + 
  theme(legend.position = "bottom",
        legend.title = element_text())

ggplotly(plot1)                #make a plotly plot from ggplot using ggplotly
```

Column {data-width=500}
-----------------------------------------------------------------------
### Top 10 aisles reordered from within 7 days
```{r message = FALSE, warning = FALSE, echo = FALSE}
#barplot for top 20 aisles getting reordered within 7 days 
instacart_df_clean %>% 
filter(reordered == 1 & days_since_prior_order < 8) %>% #filter out products that are reordered within 7 days
  count(aisle) %>%                #group and count the number of aisles with such criteria
  top_n(20) %>%                   #get top 20 aisles with most reorders
  mutate(aisle = 
          fct_reorder(
            aisle, desc(n)),      #order level based on count
        text_label =              #set text labels for plot_ly
          str_c("Count: ", n, " products")) %>% 
  plot_ly(x = ~aisle,             #make plot_ly scatter plot
          y = ~ n,
          type = "scatter", mode = "markers",
          text = ~text_label, 
          alpha = 0.9) %>%
  layout(yaxis =                  #format plot_ly plot 
           list(title = "Number of reorders"),
         xaxis = 
           list(title = "Aisle name", 
                tickangle = 25)
         )
```

-----------------------------------------------------------------------
### Total number of orders per day by hour
```{r, warning = FALSE, message = FALSE, echo = FALSE}
#plot for total number of orders per day by hour 
instacart_df_clean %>% 
  group_by(order_dow,             #group by day and hour of order
           order_hour_of_day) %>% 
  summarize(total = n()) %>%      #count number of orders per group
  ungroup() %>% 
  mutate(text_label =             #set text_label for plot_ly plot
           str_c("Hour of day: ", order_hour_of_day, "h", 
                 "\nTotal orders: ", total, " orders")) %>%
  plot_ly(x = ~order_hour_of_day, #create plot_ly line plot
          y = ~total,
          type = "scatter", mode = "line",
          color = ~order_dow,
          text = ~text_label, 
          alpha = 0.7) %>%
  layout(xaxis = list(title = "Hour of the day", tickangle = 0),
         yaxis = list(title = "Order count")
         )
```

