---
title: ""
output:
  html_document:
    toc: true
    toc_float: true
    theme: cosmo 
editor_options: 
  chunk_output_type: console
---

## Public health projects

 - "Immunity and Cognitive Function Among Elderly People:
A Cross-Sectional Study" -- by *Ngoc Duong, Alicia Lewis, and Kathryn Burke* [link](./Biol 288_final project.pdf)

 - "Socioeconomic factors and viral hepatitis B
infection" -- by *Ngoc Duong* [link](./Biostatistics_final project report_Ngoc.pdf)

 - "Hepatitis B knowledge and medical practices among healthcare professionals in Vietnam: a cross-sectional
study" -- by *Ngoc Duong and Ping-Jui Ko* [link](./Asian Liver Center report_Ngoc Duong.pdf) 

## Economics projects

 - '“Excuse Me, I’m Sorry”: The Effects of Apologies and Excuses for Mistakes' -- by *Ngoc Duong, Margaux Lieser, Yicai Wang, and Karmen Hutchinson* [link](./ECON 333 Final Paper.pdf)

 - "Multivariate Regression Modeling to Estimate Home Prices in Brooklyn" -- by *Ngoc Duong and Alexander Koo* [link](./Math242_summary_report_Alex&Ngoc.pdf)
